### PR TITLE
Prevent Android crashes

### PR DESCRIPTION
**Pull request by dabit1**

### CODE REVIEW

**Comment by christopherdro** [comment]
@dabit1 What sort of crashes does this prevent?

**Comment by dabit1** [comment]
I don't know why but sometimes my app crashed when I loaded maps. Reading logcat I found that `map` var was null.

**Comment by dabit1** [comment]
Besides, other methods in the same class checks if map var is null before do an actions, likely for the same reason.

**Comment by christopherdro** [comment]
I don't see this check happening anywhere else in the class. Can you show me where you see this?

You can do a check for `ref` in JS before calling any of these methods.

**Comment by liyuanhust** [comment]
Why this pr was not merged? This crash happens many times on my HTC devices.
Now I have to do some tricky method to prevent the crash.
Pls merge the pr !

Fatal Exception: java.lang.NullPointerExceptionAttempt to invoke virtual method 'void com.google.android.gms.maps.GoogleMap.setPadding(int, int, int, int)' on a null object reference Raw Text
--
  | com.airbnb.android.react.maps.AirMapView.fitToCoordinates (AirMapView.java:655)
  | com.airbnb.android.react.maps.AirMapManager.receiveCommand (AirMapManager.java:236)
  | com.airbnb.android.react.maps.AirMapManager.receiveCommand (AirMapManager.java:27)

**Comment by christopherdro** [comment]
Thanks for submitting this and sorry for the late response. An updated PR has been submitted here. 

https://github.com/airbnb/react-native-maps/pull/1835

**Pull request closed without merging**
