### PR TITLE
fix #453

### LINKED ISSUE #453: Android: first instance of the map overlaps everything when have another map in a different scene.
Hi guys, 

I know you have lots of issues already to work on, but here is another one.

I'm using RN 0.31 with latest maps and was finally able to get my map to show up on Android with a Browser Key.

I also use react-native-router-flux and I have two scenes with maps. When I switch to the second scene, the map from the first one is frozen on top of it. I can tap/drag the map behind it and everything, but can't see what I am tapping because of this lag. If I remove the map from the second screen - everything works fine.

Any ideas or workarounds?

Thanks, 
Alex.

### PR DESCRIPTION
**Pull request by fdnhkj**
This commit fixes the issue #453.
Tested with 
``` json
  "dependencies": {
    "react": "15.3.1",
    "react-native": "^0.32.0",
    "react-native-maps": "^0.8.2",
    "react-native-router-flux": "^3.35.0"
  }
```

### CODE REVIEW

**Comment by jeveloper** [comment]
Looks good to me.

@spikebrehm  your turn :)

**Comment by spikebrehm** [comment]
Thanks for the contribution!

This essentially reverts https://github.com/airbnb/react-native-maps/pull/449.

@felipecsl can you TAL?

**Comment by spikebrehm** [comment]
There's now a merge conflict. @fdnhkj would you mind rebasing?

**Comment by fdnhkj** [comment]
@spikebrehm Done :)

**Pull request merged**
