### PR TITLE
Fixes #470. Support legalLabelInsets on Apple Maps

### LINKED ISSUE #470: Is it possible to change  the position of legalLabelInsets on the bottom left corner of the map, and also changing the location of the button for centering the map to user current Location?

### PR DESCRIPTION
**Pull request by scarlac**
Fixes #470. This will add support for `legalLabelInsets` prop on iOS with Apple Maps. Code is adapted from RN core.

### CODE REVIEW

**Comment by gilbox** [comment]
Thanks! We should probably avoid `->` notation. Would you mind adding an example for this?

**Comment by scarlac** [comment]
@gilbox Yeah, let's keep it consistent. I've removed it.

**Comment by gilbox** [comment]
@scarlac will you be able to add an example?

**Comment by scarlac** [comment]
@gilbox Ah! I am assuming you mean updating the documentation. Yes, I'll get right on it tomorrow and update this PR :)

**Comment by gilbox** [comment]
@scarlac I was talking about adding an example in the `example/examples` dir. That's how I smoke-test PRs since we don't have specs.

**Comment by scarlac** [comment]
@gilbox I've added an example to demonstrate the usefulness of the `legalLabelInsets`. I think it's fairly simple while showing a very realistic scenario of when it could be of use. Personally, I'm using it in an advanced way but opted for simplicity in the example, for the sake of understanding.

Let me know if there's more you need before it's ready for a merging.

**Comment by gilbox** [comment]
lgtm but I'd like to get a second opinion re: the async op

**Comment by gilbox** [comment]
thanks @scarlac ( ◠‿◠ )

**Comment by scarlac** [comment]
My pleasure! 👍

**Pull request merged**
