### PR TITLE
Fix/nullability

### PR DESCRIPTION
**Pull request by simonmitchell**
Fixes compiler error with trying to specify nullability on a BOOL

### CODE REVIEW

**Comment by spikebrehm** [comment]
@simonmitchell in #611 you said that this fix is necessary to get the project to build with CocoaPods.  How does this change affect CocoaPods builds?

In [this commit](https://github.com/airbnb/react-native-maps/commit/36476025deed5faac2a469c2fa6076ad4e9802aa#diff-a537138599914b3a6ff2af1efb65be4eR442), @naoufal added default values to the `fitToCoordinates` options, so `animated` should not be `null` unless you're manually passing it in, right?

**Comment by gilbox** [comment]
@spikebrehm i had to make this same fix for a from-scratch simple non-cocoapods test project.

**Comment by spikebrehm** [comment]
👍

**Comment by simonmitchell** [comment]
Yeah sorry for the confusion, wasn't related to the CocoaPods issue, was just telling that person that even after I used CocoaPods I still needed to make changes.

**Pull request merged**
