### PR TITLE
Fix/convert import

### PR DESCRIPTION
**Pull request by simonmitchell**
This fixes an issue where the file `RCTConvert+MapKit` was renamed to `RCTConvert+AirMap` but the project file changes were not committed. See issue: https://github.com/airbnb/react-native-maps/issues/1213

### CODE REVIEW

**Comment by silviopaganini** [comment]
please merge!

**Comment by timurridjanovic** [comment]
This works! Please merge.

**Comment by rgehan** [comment]
Please merge this PR, it's pretty annoying :/

**Comment by derekbrown** [comment]
@lelandrichardson Can you merge this ASAP?

**Comment by sroze** [comment]
I can confirm this solves this issue that occurs when you install a fresh version of `react-native-maps` ! LGTM 👍

**Comment by willdurand** [comment]
Same here ❤️

**Comment by bbubn** [comment]
We need this merge ... Please please please %)

**Comment by tonyhb** [comment]
Dupe of #1195 which is merged

**Comment by christopherdro** [comment]
Thanks for the PR! But I merged

**Pull request closed without merging**
