### PR TITLE
setNativeProps, marker opacity, nested components

### PR DESCRIPTION
**Pull request by unboundfire**
* Added setNativeProps convenience support for circle, polyline, polygon, marker
* Added support to help create custom overlay components by nesting with React Components
* Added opacity props on Markers

### CODE REVIEW

**Comment by volkangurel** [comment]
:+1:

**Comment by Stonelinks** [comment]
:+1:

**Comment by unboundfire** [comment]
Any update on this?

**Comment by spikebrehm** [comment]
Awesome, thanks for this! 🍻

**Pull request merged**
