### PR TITLE
IOS Google Map styling

### LINKED ISSUE #781: MapStyleOptions
hi , there. as of [september_21_2016](https://developers.google.com/maps/documentation/android-api/releases#september_21_2016) google has made it possible to give styling to mobile maps. please make this possible !!

### PR DESCRIPTION
**Pull request by ali-alamine**
Adds support  to google map styling for ios.

fix #781

### CODE REVIEW

**Comment by gilbox** [comment]
image

**Comment by nrathi** [comment]
Thanks for this change! I think I'm missing something though -- how do I tell iOS to use Google Maps instead of Apple?

**Comment by gilbox** [comment]
`provider={MapView.PROVIDER_GOOGLE}`

**Comment by nrathi** [comment]
Hmm this isn't working for me. Is it because it's not apart of the latest release? Here's my code: 

```
    return (
      <View style={BaseStyles.container}>
        <MapView
          provider={MapView.PROVIDER_GOOGLE}
          style={StyleSheet.absoluteFill}
          customMapStyle={mapStyle}
          region={this.state.mapRegion}
          showsUserLocation={true}>
          {fromMarker}
          {toMarker}
          {polyLine}
        </MapView>
        {clearButton}
        <View style={styles.view}>
          {whereTo}
          {timePicker}
        </View>
        {parkHere}
        {resultSet}
      </View>
    );
  }

const mapStyle = [ // some JSON from https://mapstyle.withgoogle.com/ ];
```

**Comment by ali-alamine** [comment]
@nrathi no it's not yet

@gilbox Any chance of pushing a new release to npm? I think a lot of people need this.

**Comment by mCzolko** [comment]
🐑  🇮🇹  
🙏 
@gilbox do us the favor of release 😃

**Comment by mCzolko** [comment]
@spikebrehm could you help gilbox with releasing this to NPM?

**Comment by nrathi** [comment]
https://github.com/airbnb/react-native-maps/pull/722/files

This would also be great to have.

**Comment by gilbox** [comment]
v0.12.1 is published

**Pull request merged**
