### PR TITLE
Added Typescript Definitions

### PR DESCRIPTION
**Pull request by PaitoAnderson**
Not sure if you are interested in supporting Typescript users, but I did this while using your library for myself and thought I would share. Thanks!

### CODE REVIEW

**Comment by gpeal** [comment]
@PaitoAnderson Thanks for doing this!

**Comment by PaitoAnderson** [comment]
Thanks for merging this @gpeal!

**Comment by infinitec123** [comment]
I am getting an error on the line: export default MapView. The error is 

"Exports and export assignments are not permitted in module augmentations". Could you please guide me on this? My tsconfig is as follows:


{
  "compileOnSave": true,
  "compilerOptions": {
    "target": "es2015",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "module": "commonjs",
    "moduleResolution": "node",
    "allowJs": true,
    "sourceMap": true,
    "jsx": "react-native",
    
    "outDir": "./artifacts",
    "rootDirs": [
      "./",
      "./src",
      "./src/**/*",
      "./modules/**/*"
    ],
    "removeComments": true,
    "preserveConstEnums": true,
    "noImplicitReturns": true,
    "noUnusedParameters": true,
    "noUnusedLocals": true,
    "noImplicitAny": true,
    "noImplicitThis": true,
    "strict": true,
    "strictNullChecks": true,
    "alwaysStrict": true,
    "allowSyntheticDefaultImports": true
  },
  "types": [
    "react",
    "react-native",
    "jest"
  ],
  "include": [
    "src/**/*",
    "modules/**/*"
  ],
  "exclude": [
    "android",
    "ios",
    "artifacts",
    "node_modules",
    "index.android.js",
    "index.ios.js"
  ]
}

**Comment by PaitoAnderson** [comment]
@infinitec123:

Unfortunately, you will get this error until #1687 is merged.

Here is my tsconfig.json though if you're curious:

```
{
    "compilerOptions": {
  /* Basic Options */
      "target": "es2015",                       /* Specify ECMAScript target version: 'ES3' (default), 'ES5', 'ES2015', 'ES2016', 'ES2017', or 'ESNEXT'. */
      "module": "es2015",                       /* Specify module code generation: 'commonjs', 'amd', 'system', 'umd' or 'es2015'. */
      // "lib": [],                             /* Specify library files to be included in the compilation:  */
      "allowJs": true,                          /* Allow javascript files to be compiled. */
      // "checkJs": true,                       /* Report errors in .js files. */
      "jsx": "react-native",                    /* Specify JSX code generation: 'preserve', 'react-native', or 'react'. */
      // "declaration": true,                   /* Generates corresponding '.d.ts' file. */
      "sourceMap": true,                        /* Generates corresponding '.map' file. */
      // "outFile": "./",                       /* Concatenate and emit output to single file. */
      // "outDir": "./build",                   /* Redirect output structure to the directory. */
      "rootDir": "./src",                       /* Specify the root directory of input files. Use to control the output directory structure with --outDir. */
      "removeComments": false,                  /* Do not emit comments to output. */
      // "noEmit": true,                        /* Do not emit outputs. */
      // "importHelpers": true,                 /* Import emit helpers from 'tslib'. */
      // "downlevelIteration": true,            /* Provide full support for iterables in 'for-of', spread, and destructuring when targeting 'ES5' or 'ES3'. */
      // "isolatedModules": true,               /* Transpile each file as a separate module (similar to 'ts.transpileModule'). */
  
      /* Strict Type-Checking Options */
      "strict": true,                           /* Enable all strict type-checking options. */
      "noImplicitAny": true,                    /* Raise error on expressions and declarations with an implied 'any' type. */
      "strictNullChecks": true,                 /* Enable strict null checks. */
      "noImplicitThis": true,                   /* Raise error on 'this' expressions with an implied 'any' type. */
      "alwaysStrict": true,                     /* Parse in strict mode and emit "use strict" for each source file. */
  
      /* Additional Checks */
      // "noUnusedLocals": true,                /* Report errors on unused locals. */
      // "noUnusedParameters": true,            /* Report errors on unused parameters. */
      // "noImplicitReturns": true,             /* Report error when not all code paths in function return a value. */
      // "noFallthroughCasesInSwitch": true,    /* Report errors for fallthrough cases in switch statement. */
  
      /* Module Resolution Options */
      "moduleResolution": "node",               /* Specify module resolution strategy: 'node' (Node.js) or 'classic' (TypeScript pre-1.6). */
      // "baseUrl": "./",                       /* Base directory to resolve non-absolute module names. */
      // "paths": {},                           /* A series of entries which re-map imports to lookup locations relative to the 'baseUrl'. */
      // "rootDirs": [],                        /* List of root folders whose combined content represents the structure of the project at runtime. */
      // "typeRoots": [],                       /* List of folders to include type definitions from. */
      // "types": [],                           /* Type declaration files to be included in compilation. */
      "allowSyntheticDefaultImports": true      /* Allow default imports from modules with no default export. This does not affect code emit, just typechecking. */
  
      /* Source Map Options */
      // "sourceRoot": "./",                    /* Specify the location where debugger should locate TypeScript files instead of source locations. */
      // "mapRoot": "./",                       /* Specify the location where debugger should locate map files instead of generated locations. */
      // "inlineSourceMap": true,               /* Emit a single file with source maps instead of having a separate file. */
      // "inlineSources": true,                 /* Emit the source alongside the sourcemaps within a single file; requires '--inlineSourceMap' or '--sourceMap' to be set. */
  
      /* Experimental Options */
      // "experimentalDecorators": true,        /* Enables experimental support for ES7 decorators. */
      // "emitDecoratorMetadata": true,         /* Enables experimental support for emitting type metadata for decorators. */
    }
  }
```

**Pull request merged**
