### PR TITLE
Added new method: setMapType

### PR DESCRIPTION
**Pull request by tpisto**
This method allows fast and efficient way to change the underlying map type. Supported map types are  'standard', 'satellite', 'hybrid', 'terrain'

### CODE REVIEW

**Comment by spikebrehm** [comment]
Thanks for the PR @tpisto!

I'm curious, what's the use case for an imperative `setMapType()` method?  Is the `mapType` prop not sufficient for changing the map type?

**Comment by jeveloper** [comment]
I'm confused, but this is already present and works great on both platforms. I can attest to that.

**Comment by tpisto** [comment]
@spikebrehm Thank you for the comments. I found the imperative method very convenient and fast if you have following structure (taken from the front page readme.md) and big number of markers:

```
<MapView
  region={this.state.region}
  onRegionChange={this.onRegionChange}
>
  {this.state.markers.map(marker => (
    <MapView.Marker
      coordinate={marker.latlng}
      title={marker.title}
      description={marker.description}
    >
    <MapView.Callout>
        <MyCustomCalloutView {...marker} />
     </MapView.Callout>
   </MapView.Marker>
  ))}
</MapView>
```

There are ways to overcome this performance problem in other ways too, but for me this method offered usage convenience. That could be just me - but I thought maybe others could find this useful too. But if I'm wrong, it's ok just close this PR.

**Comment by spikebrehm** [comment]
I don't see where `setMapType()` is called in your example.  Can you provide some sample code of how you're using it, so I can understand the performance implications?

Here's what it would look like to use the `mapType` prop:

```js
<MapView
  region={this.state.region}
  onRegionChange={this.onRegionChange}
  mapType={this.state.mapType}
>
  {this.state.markers.map(marker => (
    <MapView.Marker
      coordinate={marker.latlng}
      title={marker.title}
      description={marker.description}
    >
    <MapView.Callout>
        <MyCustomCalloutView {...marker} />
     </MapView.Callout>
   </MapView.Marker>
  ))}
</MapView>
```

**Comment by spikebrehm** [comment]
@tpisto closing for now.  Feel free to re-open if you think this is necessary.

**Pull request closed without merging**
