### PR TITLE
Wrap and protect onDestroy, since it can sometimes crash when hitting the back-button

### PR DESCRIPTION
**Pull request by mikelambert**
This should fix: https://github.com/airbnb/react-native-maps/issues/414

### CODE REVIEW

**Comment by christopherdro** [comment]
@mikelambert Thanks for the PR! Looks like an extra commit got tacked onto your PR and is causing conflicts.

Could you update your PR so it only includes https://github.com/airbnb/react-native-maps/pull/663/commits/44bce854234d34ca6e654d59ed99e4b80329275f

**Comment by mikelambert** [comment]
Not sure what happened. Fixed.

**Comment by mikelambert** [comment]
Ping?

**Comment by mikelambert** [comment]
Oh, sorry, I see this was fixed in https://github.com/airbnb/react-native-maps/pull/694 .  Closing...

**Pull request closed without merging**
